version: "3.5"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "Europe/London"
      # WEBPASSWORD: "password"
    # Volumes store your data between container upgrades
    volumes:
      - pihole_vol:/etc/pihole/
      - dnsmasq_vol:/etc/dnsmasq.d/
    network_mode: "bridge"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  pihole_vol:
    driver: local
    driver_opts:
      type: none
      device: $HOME/pihole/pihole
      o: bind
  dnsmasq_vol:
    driver: local
    driver_opts:
      type: none
      device: $HOME/pihole/dnsmasq.d
      o: bind

